services:
  - type: web
    name: brightventurez
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn brightventurez.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: upej7vb)dpt%_ky7axfbd*)le&fzp()k0k#!@p3($&ti9%hx%&
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: brightventurez-db
          property: connectionString

databases:
  - name: brightventurez-db
    plan: free
